#before_script:
#    - docker-php-ext-enable xdebug

php-5.3:
  image: tetraweb/php:5.3
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh

php-5.4:
  image: tetraweb/php:5.4
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh

php-5.5:
  image: tetraweb/php:5.5
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh

php-5.6:
  image: tetraweb/php:5.6
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh

php-7.0:
  image: tetraweb/php:7.0
  services:
    - tetraweb/mysql
  script:
    - _tests/test.sh
